spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8  #数据库地址+库名
    username: root #数据库名称
    password: mysql #数据库密码
# 日志打印级别
logging:
  level:
    root: debug
