-- CREATE DATABASE `demo` CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
DROP TABLE IF EXISTS tbl_person;
CREATE TABLE tbl_person(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
address VARCHAR(100) NOT NULL DEFAULT '' COMMENT '地址',
age INT(4) NOT NULL DEFAULT 0 COMMENT '年龄',
name VARCHAR(10) NOT NULL DEFAULT '' COMMENT '名称'
);
